services:
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: starter_database
    hostname: starter_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      retries: 10
      start_period: 5s
      timeout: 3s
